#!/bin/sh

ENABLED=yes
PROCS=client_linux_arm5
ARGS="-c /opt/etc/kcptun-router.json"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func